project:
  type: website
  output-dir: _site


website:
  title: "Nuhaadh Mahid"
  site-url: https://nuhaadhmahid.com/
  repo-url: https://github.com/nuhaadhmahid/Website
  open-graph: true
  navbar:
    search: true
    left:
      - text: "Blog"
        file: blog.qmd
      - text: "Research"
        file: research.qmd

format:
  html:
    theme: lux
    css: styles/styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    smooth-scroll: true

render: 
  freeze: true


