project:
  type: website
  output-dir: _site


website:
  title: "Nuhaadh Mahid"
  navbar:
    search: true
    left:
      - publications.qmd
    

format:
  html:
    theme: lux
    css: styles.css
    toc: true



