<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-12-30">

<title>tiny GPT – Nuhaadh Mahid</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-cc1d64809b8ed731f92ea1275fe9f05b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles/styles.css">
<link rel="stylesheet" href="../../styles/jupyter_styles.css">
<meta property="og:title" content="tiny GPT – Nuhaadh Mahid">
<meta property="og:description" content="">
<meta property="og:image" content="https://nuhaadhmahid.com/images/ChatGPT4_tokens.png">
<meta property="og:site_name" content="Nuhaadh Mahid">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Nuhaadh Mahid</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#setting-the-environment" id="toc-setting-the-environment" class="nav-link active" data-scroll-target="#setting-the-environment">Setting the Environment</a></li>
  <li><a href="#preparing-the-dataset" id="toc-preparing-the-dataset" class="nav-link" data-scroll-target="#preparing-the-dataset">Preparing the Dataset</a></li>
  <li><a href="#tokenization" id="toc-tokenization" class="nav-link" data-scroll-target="#tokenization">Tokenization</a></li>
  <li><a href="#embedding" id="toc-embedding" class="nav-link" data-scroll-target="#embedding">Embedding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">tiny GPT</h1>
  <div class="quarto-categories">
    <div class="quarto-category">PyTorch</div>
    <div class="quarto-category">NLP</div>
    <div class="quarto-category">GPT</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 30, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="setting-the-environment" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="setting-the-environment">Setting the Environment</h2>
<p>I start by installing CUDA inside Windows Subsystem for Linux (WSL)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and then installing PyTorch with CUDA support<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Once I’ve installed the CUDA toolkit and PyTorch, I verify the CUDA version and PyTorch access to CUDA using the following command:</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;For instructions on installing CUDA in WSL, see the <a href="https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#wsl-installation">NVIDIA documentation</a>.</p></div><div id="fn2"><p><sup>2</sup>&nbsp;For instructions on installing PyTorch with CUDA support, see the <a href="https://pytorch.org/get-started/locally/">PyTorch installation guide</a>.</p></div></div><div id="39062c2e" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="op">!</span>nvidia<span class="op">-</span>smi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mon Dec 29 16:04:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.07             Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2050        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0              8W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+</code></pre>
</div>
</div>
<div id="ade9d370" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="op">!</span>python3 <span class="op">-</span>c <span class="st">"import torch; print(torch.__version__); print(torch.cuda.is_available())"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.9.1+cu130
True</code></pre>
</div>
</div>
<p>I have CUDA version 13.0 and PyTorch 2.9.1+cu130 installed. I start by importing the necessary libraries to the notebook:</p>
<div id="7e45786b" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># import packages</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="im">import</span> os</span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="im">import</span> json</span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="im">import</span> multiprocessing <span class="im">as</span> mp</span>
<span id="cb5-5"><a href="#cb5-5"></a></span>
<span id="cb5-6"><a href="#cb5-6"></a><span class="im">import</span> torch</span>
<span id="cb5-7"><a href="#cb5-7"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb5-9"><a href="#cb5-9"></a></span>
<span id="cb5-10"><a href="#cb5-10"></a><span class="co"># define options</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>device <span class="op">=</span> torch.device(<span class="st">"cuda"</span> <span class="cf">if</span> torch.cuda.is_available() <span class="cf">else</span> <span class="st">"cpu"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="preparing-the-dataset" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="preparing-the-dataset">Preparing the Dataset</h2>
<p>I will work with a dataset of BBC news articles <span class="citation" data-cites="Greene2006PracticalSolutionsProblem"><a href="#ref-Greene2006PracticalSolutionsProblem" role="doc-biblioref">[1]</a></span>. My goal is to train a tiny GPT model to generate news articles similar to those in the dataset, given an arbitrary title. Let’s start with downloading the dataset and unpacking it:</p>
<div class="no-row-height column-margin column-container"><div id="ref-Greene2006PracticalSolutionsProblem" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">D. Greene and P. Cunningham, <span>“Practical solutions to the problem of diagonal dominance in kernel document clustering,”</span> in <em>Proc. 23rd international conference on machine learning (ICML’06)</em>, 2006, pp. 377–384, [Online]. Available: <a href="http://mlg.ucd.ie/datasets/bbc.html">http://mlg.ucd.ie/datasets/bbc.html</a>.</div>
</div></div><div id="17d2c189" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># !mkdir -p datasets</span></span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co"># !wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip -O datasets/bbc-fulltext.zip -nv</span></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># !unzip -q datasets/bbc-fulltext.zip -d datasets/</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="co"># !rm datasets/bbc-fulltext.zip</span></span>
<span id="cb6-6"><a href="#cb6-6"></a></span>
<span id="cb6-7"><a href="#cb6-7"></a><span class="co"># !wget http://mlg.ucd.ie/files/datasets/bbcsport-fulltext.zip -O datasets/bbcsport-fulltext.zip -nv</span></span>
<span id="cb6-8"><a href="#cb6-8"></a><span class="co"># !unzip -q datasets/bbcsport-fulltext.zip -d datasets/</span></span>
<span id="cb6-9"><a href="#cb6-9"></a><span class="co"># !rm datasets/bbcsport-fulltext.zip</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I have downloaded two datasets: one with 2225 BBC News articles and 737 BBC Sports articles from 2004-2005. Now, I will combine all the text files into a <code>json</code> single file, with a list of articles. I use <code>multiprocessing</code> to speed up the process as there are many files to read:</p>
<div id="bda7efd2" class="cell" data-execution_count="41">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">def</span> process_file(file_path):</span>
<span id="cb7-2"><a href="#cb7-2"></a>    <span class="cf">with</span> <span class="bu">open</span>(file_path, <span class="st">'r'</span>, encoding<span class="op">=</span><span class="st">'utf-8'</span>) <span class="im">as</span> f:</span>
<span id="cb7-3"><a href="#cb7-3"></a>        article <span class="op">=</span> f.read()</span>
<span id="cb7-4"><a href="#cb7-4"></a>    <span class="cf">return</span> article</span>
<span id="cb7-5"><a href="#cb7-5"></a></span>
<span id="cb7-6"><a href="#cb7-6"></a><span class="co"># Check if dataset exists</span></span>
<span id="cb7-7"><a href="#cb7-7"></a><span class="cf">assert</span> (os.path.exists(<span class="st">'datasets/bbc'</span>) <span class="kw">and</span> os.path.exists(<span class="st">'datasets/bbcsport'</span>)), <span class="st">"Dataset not found! Please download the dataset first"</span></span>
<span id="cb7-8"><a href="#cb7-8"></a></span>
<span id="cb7-9"><a href="#cb7-9"></a><span class="co"># Get all files in the dataset directory</span></span>
<span id="cb7-10"><a href="#cb7-10"></a>file_list <span class="op">=</span> [] </span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="cf">for</span> root, dirs, files <span class="kw">in</span> os.walk(<span class="st">'datasets'</span>):</span>
<span id="cb7-12"><a href="#cb7-12"></a>    <span class="cf">for</span> <span class="bu">file</span> <span class="kw">in</span> files:</span>
<span id="cb7-13"><a href="#cb7-13"></a>        <span class="cf">if</span> <span class="bu">file</span>.startswith(<span class="st">'README'</span>) <span class="kw">or</span> <span class="bu">file</span>.endswith(<span class="st">'.json'</span>): <span class="co"># skip README files, and existing json files</span></span>
<span id="cb7-14"><a href="#cb7-14"></a>            <span class="cf">continue</span></span>
<span id="cb7-15"><a href="#cb7-15"></a>        <span class="cf">else</span>:</span>
<span id="cb7-16"><a href="#cb7-16"></a>            file_list.append(os.path.join(root, <span class="bu">file</span>))</span>
<span id="cb7-17"><a href="#cb7-17"></a></span>
<span id="cb7-18"><a href="#cb7-18"></a><span class="co"># Read and process files in parallel</span></span>
<span id="cb7-19"><a href="#cb7-19"></a>pool <span class="op">=</span> mp.Pool(processes<span class="op">=</span>os.cpu_count()<span class="op">-</span><span class="dv">4</span>) <span class="co"># I have 16 CPU cores, here I am using 12 cores</span></span>
<span id="cb7-20"><a href="#cb7-20"></a>jobs <span class="op">=</span> pool.map_async(process_file, file_list)</span>
<span id="cb7-21"><a href="#cb7-21"></a>pool.close()</span>
<span id="cb7-22"><a href="#cb7-22"></a>pool.join() </span>
<span id="cb7-23"><a href="#cb7-23"></a></span>
<span id="cb7-24"><a href="#cb7-24"></a><span class="co"># Collect results and save in a single json file</span></span>
<span id="cb7-25"><a href="#cb7-25"></a>dataset <span class="op">=</span> jobs.get()</span>
<span id="cb7-26"><a href="#cb7-26"></a>json.dump(dataset, <span class="bu">open</span>(<span class="st">'datasets/dataset.json'</span>, <span class="st">'w'</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Before we proceed, let’s take a look at a sample article from the dataset, as shown below:</p>
<div id="3879e67f" class="cell" data-execution_count="43">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Test loading the processed dataset</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>dataset <span class="op">=</span> json.load(<span class="bu">open</span>(<span class="st">'datasets/dataset.json'</span>, <span class="st">'r'</span>))</span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="bu">print</span>(<span class="ss">f"Here is the first article from the dataset of </span><span class="sc">{</span><span class="bu">len</span>(dataset)<span class="sc">}</span><span class="ss">: </span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="bu">print</span>(dataset[<span class="dv">0</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Here is the first article from the dataset of 2962: 

Looks and music to drive mobiles

Mobile phones are still enjoying a boom time in sales, according to research from technology analysts Gartner.

More than 674 million mobiles were sold last year globally, said the report, the highest total sold to date. The figure was 30% more than in 2003 and surpassed even the most optimistic predictions, Gartner said. Good design and the look of a mobile, as well as new services such as music downloads, could go some way to pushing up sales in 2005, said analysts. Although people were still looking for better replacement phones, there was evidence, according to Gartner, that some markets were seeing a slow-down in replacement sales.

"All the markets grew apart from Japan which shows that replacement sales are continuing in western Europe," mobile analyst Carolina Milanesi told the BBC News website. "Japan is where north America and western European markets can be in a couple of years' time. "They already have TV, music, ringtones, cameras, and all that we can think of on mobiles, so people have stopped buying replacement phones."

But there could be a slight slowdown in sales in European and US markets too, according to Gartner, as people wait to see what comes next in mobile technology. This means mobile companies have to think carefully about what they are offering in new models so that people see a compelling reason to upgrade, said Gartner. Third generation mobiles (3G) with the ability to handle large amounts of data transfer, like video, could drive people into upgrading their phones, but Ms Milanesi said it was difficult to say how quickly that would happen. "At the end of the day, people have cameras and colour screens on mobiles and for the majority of people out there who don't really care about technology the speed of data to a phone is not critical." Nor would the rush to produce two or three megapixel camera phones be a reason for mobile owners to upgrade on its own. The majority of camera phone models are not at the stage where they can compete with digital cameras which also have flashes and zooms.

More likely to drive sales in 2005 would be the attention to design and aesthetics, as well as music services. The Motorola Razr V3 phone was typical of the attention to design that would be more commonplace in 2005, she added. This was not a "women's thing", she said, but a desire from men and women to have a gadget that is a form of self-expression too. It was not just about how the phone functioned, but about what it said about its owner. "Western Europe has always been a market which is quite attentive to design," said Ms Milanesi.

"People are after something that is nice-looking, and together with that, there is the entertainment side. "This year music will have a part to play in this." The market for full-track music downloads was worth just $20 million (£10.5 million) in 2004, but is set to be worth $1.8 billion (£9.4 million) by 2009, according to Jupiter Research. Sony Ericsson just released its Walkman branded mobile phone, the W800, which combines a digital music player with up to 30 hours' battery life, and a two megapixel camera. In July last year, Motorola and Apple announced a version of iTunes online music downloading service would be released which would be compatible with Motorola mobile phones. Apple said the new iTunes music player would become Motorola's standard music application for its music phones. But the challenge will be balancing storage capacity with battery life if mobile music hopes to compete with digital music players like the iPod. Ms Milanesi said more models would likely be released in the coming year with hard drives. But they would be more likely to compete with the smaller capacity music players that have around four gigabyte storage capacity, which would not put too much strain on battery life.
</code></pre>
</div>
</div>
<p>Notice that we have a list of articles, each containing a title, a summary line and the corresponding text. Each article is a list of words, spaces, and newline characters (e.g., <code>\n</code>). To train our tiny GPT model, we need to represent this text data in for of numbers. The easiest way to do this is through building a look-up table that maps each unique item of text to a unique integer. This process is called tokenization.</p>
</section>
<section id="tokenization" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="tokenization">Tokenization</h2>
<p>At the lowest level, the articles are a string of characters. These characters join together to make words, and words join together to make sentences, and so on. With character-level tokenisation, I represent each unique character (e.g., ‘a’, ‘b’, ‘c’, …,‘!’,‘?’, etc.) with a unique integer. The model will then learn to generate text one character at a time. This gives a smaller number of unique tokens to represent (i.e., the vocabulary size). However, since we are generating text one character at a time, the sequence of characters required to make a sentence will be longer. Alternatively, if I use a word-level tokenization, where each unique word is represented by a unique integer. This would give us a larger vocabulary size but a shorter sequence length. Let’s break this down further with an example. Below I show the first 10 items in a character-level and word-level tokenization:</p>
<div id="fb19eb79" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1"></a>first_article <span class="op">=</span> dataset[<span class="dv">0</span>]</span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The first article has </span><span class="sc">{</span><span class="bu">len</span>(<span class="bu">set</span>(first_article.split()))<span class="sc">}</span><span class="ss"> words, and </span><span class="sc">{</span><span class="bu">len</span>(<span class="bu">set</span>(first_article))<span class="sc">}</span><span class="ss"> characters."</span>)</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a>char_tokens <span class="op">=</span> <span class="bu">list</span>(first_article)</span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The first 10 character tokens are: </span><span class="ch">\n</span><span class="sc">{</span>char_tokens[:<span class="dv">10</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-6"><a href="#cb10-6"></a></span>
<span id="cb10-7"><a href="#cb10-7"></a>word_tokens <span class="op">=</span> first_article.split()</span>
<span id="cb10-8"><a href="#cb10-8"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">The first 10 word tokens are: </span><span class="ch">\n</span><span class="sc">{</span>word_tokens[:<span class="dv">10</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
The first article has 326 words, and 65 characters.

The first 10 character tokens are: 
['L', 'o', 'o', 'k', 's', ' ', 'a', 'n', 'd', ' ']

The first 10 word tokens are: 
['Looks', 'and', 'music', 'to', 'drive', 'mobiles', 'Mobile', 'phones', 'are', 'still']</code></pre>
</div>
</div>
<p>The work-level tokenisation present much more information with just 10 items compared to the character-level tokenisation. Hence, there is a trade-off between vocabulary size and sequence length when choosing between level of tokenisation used in natural language processing (NLP). For better performance, the commercial GPT models use sub-word tokenisation, which is a hybrid approach that balances vocabulary size and sequence length <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. It combines the word with the preceding spaces as a single token, as shown below:</p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;For more information on sub-word tokenization, see the <a href="https://platform.openai.com/tokenizer">Tokenizer from OpenAI</a>.</p></div></div><div id="fig-chatgpt4_tokens" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-cap="ChatGPT-4 Tokenisation Example">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chatgpt4_tokens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../..\images/ChatGPT4_tokens.png" class="img-fluid figure-img" data-fig-cap="ChatGPT-4 Tokenisation Example">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chatgpt4_tokens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: ChatGPT-4 Tokenisation
</figcaption>
</figure>
</div>
<p>For simplicity, I will start with a character-level tokenisation for this tiny GPT model. I will add two special tokens to the vocabulary: <code>&lt;startoftext&gt;</code> and <code>&lt;endoftext&gt;</code>, which indicate the start and end of an article, respectively. These tokens help the model understand where an article begins and ends during training and generation. Let’s build the character-level tokenizer:</p>
<div id="83cfea85" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># Combine all articles</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>data <span class="op">=</span> []</span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="cf">for</span> article <span class="kw">in</span> dataset: </span>
<span id="cb12-4"><a href="#cb12-4"></a>    data.append(<span class="st">"&lt;startoftext&gt;"</span>) <span class="co"># Add start token before each article</span></span>
<span id="cb12-5"><a href="#cb12-5"></a>    data.extend(<span class="bu">list</span>(article)) <span class="co"># Extend the data list with characters from each article</span></span>
<span id="cb12-6"><a href="#cb12-6"></a>    data.append(<span class="st">"&lt;endoftext&gt;"</span>) <span class="co"># Add end token after each article</span></span>
<span id="cb12-7"><a href="#cb12-7"></a></span>
<span id="cb12-8"><a href="#cb12-8"></a><span class="co"># This is redundant, since any character that is not the data will not be trained on. I add this on make sure the model can handle all these characters at inference stage.</span></span>
<span id="cb12-9"><a href="#cb12-9"></a>characters <span class="op">=</span> [</span>
<span id="cb12-10"><a href="#cb12-10"></a>    <span class="st">'&lt;startoftext&gt;'</span>, <span class="st">'&lt;endoftext&gt;'</span>, <span class="st">'</span><span class="ch">\n</span><span class="st">'</span>, <span class="st">' '</span>, <span class="st">'.'</span>, <span class="st">','</span>, <span class="st">'!'</span>, <span class="st">'?'</span>, <span class="st">"'"</span>, <span class="st">'"'</span>, <span class="st">';'</span>, <span class="st">':'</span>, <span class="st">'-'</span>, <span class="st">'('</span>, <span class="st">')'</span>, <span class="st">'['</span>, <span class="st">']'</span>, <span class="st">'{'</span>, <span class="st">'}'</span>, </span>
<span id="cb12-11"><a href="#cb12-11"></a>    <span class="st">'0'</span>, <span class="st">'1'</span>, <span class="st">'2'</span>, <span class="st">'3'</span>, <span class="st">'4'</span>, <span class="st">'5'</span>, <span class="st">'6'</span>, <span class="st">'7'</span>, <span class="st">'8'</span>, <span class="st">'9'</span>, </span>
<span id="cb12-12"><a href="#cb12-12"></a>    <span class="st">'a'</span>, <span class="st">'b'</span>, <span class="st">'c'</span>, <span class="st">'d'</span>, <span class="st">'e'</span>, <span class="st">'f'</span>, <span class="st">'g'</span>, <span class="st">'h'</span>, <span class="st">'i'</span>, <span class="st">'j'</span>, <span class="st">'k'</span>, <span class="st">'l'</span>, <span class="st">'m'</span>, <span class="st">'n'</span>, <span class="st">'o'</span>, <span class="st">'p'</span>, <span class="st">'q'</span>, <span class="st">'r'</span>, <span class="st">'s'</span>, <span class="st">'t'</span>, <span class="st">'u'</span>, <span class="st">'v'</span>, <span class="st">'w'</span>, <span class="st">'x'</span>, <span class="st">'y'</span>, <span class="st">'z'</span>, </span>
<span id="cb12-13"><a href="#cb12-13"></a>    <span class="st">'A'</span>, <span class="st">'B'</span>, <span class="st">'C'</span>, <span class="st">'D'</span>, <span class="st">'E'</span>, <span class="st">'F'</span>, <span class="st">'G'</span>, <span class="st">'H'</span>, <span class="st">'I'</span>, <span class="st">'J'</span>, <span class="st">'K'</span>, <span class="st">'L'</span>, <span class="st">'M'</span>, <span class="st">'N'</span>, <span class="st">'O'</span>, <span class="st">'P'</span>, <span class="st">'Q'</span>, <span class="st">'R'</span>, <span class="st">'S'</span>, <span class="st">'T'</span>, <span class="st">'U'</span>, <span class="st">'V'</span>, <span class="st">'W'</span>, <span class="st">'X'</span>, <span class="st">'Y'</span>, <span class="st">'Z'</span></span>
<span id="cb12-14"><a href="#cb12-14"></a>    ]</span>
<span id="cb12-15"><a href="#cb12-15"></a></span>
<span id="cb12-16"><a href="#cb12-16"></a><span class="co"># Create vocabulary</span></span>
<span id="cb12-17"><a href="#cb12-17"></a>vocab <span class="op">=</span> <span class="bu">list</span>(<span class="bu">set</span>(characters).union(<span class="bu">set</span>(data))) <span class="co"># List of unique characters</span></span>
<span id="cb12-18"><a href="#cb12-18"></a><span class="bu">print</span>(<span class="ss">f'Vocab size: </span><span class="sc">{</span><span class="bu">len</span>(vocab)<span class="sc">}</span><span class="ss">'</span>) <span class="co"># Print vocabulary size and the vocabulary list</span></span>
<span id="cb12-19"><a href="#cb12-19"></a></span>
<span id="cb12-20"><a href="#cb12-20"></a><span class="co"># Average characters per article</span></span>
<span id="cb12-21"><a href="#cb12-21"></a><span class="bu">print</span>(<span class="ss">f'Total number of characters in the dataset: </span><span class="sc">{</span><span class="bu">len</span>(data)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb12-22"><a href="#cb12-22"></a>avg_chars_per_article <span class="op">=</span> <span class="bu">len</span>(data) <span class="op">/</span> <span class="bu">len</span>(dataset)</span>
<span id="cb12-23"><a href="#cb12-23"></a><span class="bu">print</span>(<span class="ss">f'Average number of characters per article: </span><span class="sc">{</span>avg_chars_per_article<span class="sc">:.0f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vocab size: 92
Total number of characters in the dataset: 6494404
Average number of characters per article: 2193</code></pre>
</div>
</div>
<p>I have 92 unique characters in total, including letters, digits, punctuation marks, spaces, and newline characters. Each article has an average of 2193 characters. This is an important metric to consider when deciding on the sequence length of text for training the model.</p>
<p>Next, I create a mapping from characters to integers and from integers to characters. These mapping processes are known as encoding and decoding, respectively. Here, I define two functions, <code>encode</code> and <code>decode</code>, to perform these mappings:</p>
<div id="8cade98b" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Encoding and decoding functions</span></span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="kw">def</span> encode(text, vocab):</span>
<span id="cb14-3"><a href="#cb14-3"></a>    char2idx <span class="op">=</span> {ch: idx <span class="cf">for</span> idx, ch <span class="kw">in</span> <span class="bu">enumerate</span>(vocab)}</span>
<span id="cb14-4"><a href="#cb14-4"></a>    <span class="cf">return</span> [char2idx[ch] <span class="cf">for</span> ch <span class="kw">in</span> text]</span>
<span id="cb14-5"><a href="#cb14-5"></a></span>
<span id="cb14-6"><a href="#cb14-6"></a><span class="kw">def</span> decode(indices, vocab):</span>
<span id="cb14-7"><a href="#cb14-7"></a>    idx2char <span class="op">=</span> {idx: ch <span class="cf">for</span> idx, ch <span class="kw">in</span> <span class="bu">enumerate</span>(vocab)}</span>
<span id="cb14-8"><a href="#cb14-8"></a>    <span class="cf">return</span> <span class="st">''</span>.join([idx2char[idx] <span class="cf">for</span> idx <span class="kw">in</span> indices])</span>
<span id="cb14-9"><a href="#cb14-9"></a></span>
<span id="cb14-10"><a href="#cb14-10"></a><span class="co"># Test encoding and decoding</span></span>
<span id="cb14-11"><a href="#cb14-11"></a>encoded <span class="op">=</span> encode(<span class="st">"Hello! This is my tiny GPT project"</span>, vocab)</span>
<span id="cb14-12"><a href="#cb14-12"></a><span class="bu">print</span>(<span class="ss">f'Encoded: </span><span class="sc">{</span>encoded<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb14-13"><a href="#cb14-13"></a></span>
<span id="cb14-14"><a href="#cb14-14"></a>decoded <span class="op">=</span> decode(encoded, vocab)</span>
<span id="cb14-15"><a href="#cb14-15"></a><span class="bu">print</span>(<span class="ss">f'Decoded: </span><span class="sc">{</span>decoded<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb14-16"><a href="#cb14-16"></a></span>
<span id="cb14-17"><a href="#cb14-17"></a><span class="co"># Encode the entire dataset</span></span>
<span id="cb14-18"><a href="#cb14-18"></a>tokens <span class="op">=</span> encode(data, vocab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Encoded: [59, 35, 91, 91, 18, 52, 53, 26, 86, 57, 44, 53, 57, 44, 53, 82, 42, 53, 43, 57, 49, 42, 53, 64, 40, 26, 53, 56, 41, 18, 39, 35, 79, 43]
Decoded: Hello! This is my tiny GPT project</code></pre>
</div>
</div>
</section>
<section id="embedding" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="embedding">Embedding</h2>
<p>Now, I have the articles represented as sequence of integers where each integer corresponds to a unique character in the vocabulary. To make predictions about the next character in the sequence, I want to represent the characters in a continuous domain. Additionally, I want to be able to make some associations between the characters. This could be like associating uppercase letters with lowercase letters, or associating punctuation marks with spaces. Essentially, I want have a way to bringing together characters that have similar context. This is done by representing each character as a vector in a continuous, high-dimensional space. This process is known as embedding, and the vector of each character is updated during training. This process allows the model to learn relationships between characters based on their context in the training data, thereby, bringing similar characters closer together in the embedding space<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;For a visual illustration, I recommend this video by 3Blue1Brown on <a href="https://www.youtube.com/shorts/FJtFZwbvkI4">how word vectors encode meaning</a>.</p></div><div id="fn5"><p><sup>5</sup>&nbsp;For more information on PyTorch’s Embedding layer, see the <a href="https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html">official documentation</a>.</p></div></div><p>Here, I define an embedding layer using PyTorch’s <code>nn.Embedding</code> class<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. The embedding layer takes the vocabulary size and the desired embedding dimension as inputs. The output of the embedding layer is a tensor of shape <code>(batch_size, sequence_length, embedding_dim)</code>, where each character in the input sequence is represented by its corresponding embedding vector.</p>
<div id="4190978a" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Define embedding layer</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>num_embeddings <span class="op">=</span> <span class="bu">len</span>(vocab)</span>
<span id="cb16-3"><a href="#cb16-3"></a>embedding_dim <span class="op">=</span> <span class="dv">16</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>Embedding <span class="op">=</span> torch.nn.Embedding(num_embeddings<span class="op">=</span>num_embeddings, embedding_dim<span class="op">=</span>embedding_dim, device<span class="op">=</span>device)</span>
<span id="cb16-5"><a href="#cb16-5"></a></span>
<span id="cb16-6"><a href="#cb16-6"></a><span class="co"># Test embedding layer  </span></span>
<span id="cb16-7"><a href="#cb16-7"></a>sample_text <span class="op">=</span> [<span class="st">"Hello"</span>, <span class="st">"World"</span>]</span>
<span id="cb16-8"><a href="#cb16-8"></a>sample_tokens <span class="op">=</span> <span class="bu">list</span>(encode(item, vocab) <span class="cf">for</span> item <span class="kw">in</span> sample_text)</span>
<span id="cb16-9"><a href="#cb16-9"></a>sample_tokens_tensor <span class="op">=</span> torch.tensor(sample_tokens, dtype<span class="op">=</span>torch.<span class="bu">long</span>, device<span class="op">=</span>device)</span>
<span id="cb16-10"><a href="#cb16-10"></a>sample_embedding <span class="op">=</span> Embedding(sample_tokens_tensor)</span>
<span id="cb16-11"><a href="#cb16-11"></a><span class="bu">print</span>(<span class="ss">f'Sample text: </span><span class="sc">{</span>sample_text<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb16-12"><a href="#cb16-12"></a><span class="bu">print</span>(<span class="ss">f'Sample indices: </span><span class="sc">{</span>sample_tokens<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb16-13"><a href="#cb16-13"></a><span class="bu">print</span>(<span class="ss">f'Sample embedding shape: </span><span class="sc">{</span>sample_embedding<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample text: ['Hello', 'World']
Sample indices: [[59, 35, 91, 91, 18], [29, 18, 41, 91, 71]]
Sample embedding shape: torch.Size([2, 5, 16])</code></pre>
</div>
</div>
<p>In the sample test above, I have 2 sequences, each with 5 characters. As each character is represented as a 16 dimensional vector in the embeddings, I have the embedding tensor of shape <code>(2, 5, 16)</code>. Here, we defined the value of <code>embedding_dim</code> as 16 and <code>num_embeddings</code> as the <code>vocab_size</code>, which is determined by the tokenization (which is 92 in this case). We did not define the sequence length or the batch size - they were inferred from the input tensor shape. To train the model, we need to fix the sequence length, as this will affect the architecture of the model. Batch size can vary during training, depending on the available memory - as it is used as way of utilizing the GPU memory efficiently.</p>
<p>P.S. To be continued…</p>



</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nuhaadhmahid\.com\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>